
CREATE TABLE "public"."AGENT" (
    "MATRICULE_AGENT" CHARACTER VARYING(7) NOT NULL,
    "CODE_AGENT" CHARACTER VARYING(5),
    "EMAIL_AGENT" CHARACTER VARYING(100),
    "NOM_AGENT" CHARACTER VARYING(100),
    "NUMERO_TELEPHONE_AGENT" INTEGER,
    "PRENOM_AGENT" CHARACTER VARYING(255),
    "CODE_SECTION" CHARACTER VARYING(3),
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3),
    CONSTRAINT "AGENT_PKEY" PRIMARY KEY ("MATRICULE_AGENT"),
    CONSTRAINT "UK_5D65N8TRVJXMH3B959PE81GDO" UNIQUE ("CODE_AGENT")
);


CREATE TABLE "public"."ARTICLE_BON_ENTREE" (
    "CODE_ARTICLE_BON_ENTREE" INTEGER NOT NULL,
    "IDENTIFIANT_B_E" CHARACTER VARYING(255) NOT NULL,
    "DATE_ENREGISTREMENT" TIMESTAMP,
    "LIBELLE_ARTICLE_BON_ENTREE" CHARACTER VARYING(255),
    "QUANTITE_ENTREE" INTEGER,
    "CODE_LIEU_VH" CHARACTER VARYING(3),
    "CODE_TYPE_OBJET" CHARACTER VARYING(5),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "ARTICLE_BON_ENTREE_PKEY" PRIMARY KEY ("CODE_ARTICLE_BON_ENTREE", "IDENTIFIANT_B_E")
);


CREATE TABLE "public"."ARTICLE_BON_POUR" (
    "CODE_ARTICLE_BON_POUR" INTEGER NOT NULL,
    "IDENTIFIANT_BON_POUR" CHARACTER VARYING(255) NOT NULL,
    "LIBELLE_ARTICLE_BON_POUR" CHARACTER VARYING(100),
    "QUANTITE_DEMANDEE" INTEGER,
    "CODE_TYPE_OBJET" CHARACTER VARYING(5),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "ARTICLE_BON_POUR_PKEY" PRIMARY KEY ("CODE_ARTICLE_BON_POUR", "IDENTIFIANT_BON_POUR")
);


CREATE TABLE "public"."ARTICLE_BON_SORTIE" (
    "CODE_ARTICLE_BON_SORTIE" INTEGER NOT NULL,
    "IDENTIFIANT_BON_SORTIE" CHARACTER VARYING(255) NOT NULL,
    "LIBELLE_ARTICLE_BON_SORTIE" CHARACTER VARYING(100),
    "DATE_ARTICLE_BON_SORTIE" DATE,
    "QUANTITE_ACCORDEE" INTEGER,
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "ARTICLE_BON_SORTIE_PKEY" PRIMARY KEY ("CODE_ARTICLE_BON_SORTIE", "IDENTIFIANT_BON_SORTIE")
);


CREATE TABLE "public"."AUTHORITIES" (
    "CODE_AUTHORITY" INTEGER NOT NULL,
    "NAME_AUTHORITIES" CHARACTER VARYING(100),
    CONSTRAINT "AUTHORITIES_PKEY" PRIMARY KEY ("CODE_AUTHORITY")
);


CREATE TABLE "public"."BON_ENTREE" (
    "IDENTIFIANT_B_E" CHARACTER VARYING(25) NOT NULL,
    "DATE_BON_ENTREE" DATE,
    "LIBELLE_BON_ENTREE" CHARACTER VARYING(255),
    "NUMERO_B_E" CHARACTER VARYING(255),
    "OBSERVATION_BON_ENTREE" CHARACTER VARYING(255),
    "IDENTIFIANT_B_L" CHARACTER VARYING(25),
    CONSTRAINT "BON_ENTREE_PKEY" PRIMARY KEY ("IDENTIFIANT_B_E"),
    CONSTRAINT "UK_SNYWQ6O1XLDKOGNLPMN20X0TQ" UNIQUE ("NUMERO_B_E")
);


CREATE TABLE "public"."BON_POUR" (
    "IDENTIFIANT_BON_POUR" CHARACTER VARYING(25) NOT NULL,
    "DATE_ARRIVE_B_L_M" DATE,
    "DATE_ARRIVE_D_L_F" DATE,
    "DATE_ARRIVE_SECTION" DATE,
    "DATE_COURRIEL_ORIGINE" DATE,
    "DATE_ENREGISTREMENT" TIMESTAMP,
    "DESCRIPTION_BON_POUR" CHARACTER VARYING(255),
    "ETAT_BON_POUR" CHARACTER VARYING(10),
    "NUMERO_ARRIVE_B_L_M" INTEGER,
    "NUMERO_ARRIVE_D_L_F" INTEGER,
    "NUMERO_ARRIVE_SECTION" INTEGER,
    "NUMERO_COURRIEL_ORIGINE" INTEGER,
    "OBJECT_COURRIEL_ORIGINE" CHARACTER VARYING(255),
    "OBSERVATION_B_L_M" CHARACTER VARYING(255),
    "OBSERVATION_D_L_F" CHARACTER VARYING(255),
    "OBSERVATION_SECTION" CHARACTER VARYING(255),
    "CODE_SECTION" CHARACTER VARYING(3),
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "BON_POUR_PKEY" PRIMARY KEY ("IDENTIFIANT_BON_POUR")
);


CREATE TABLE "public"."BON_SORTIE" (
    "IDENTIFIANT_BON_SORIE" CHARACTER VARYING(255) NOT NULL,
    "DATE_BON_SORTIE" DATE,
    "DESCRIPTION_BON_SORTIE" CHARACTER VARYING(255),
    "NUMERO_BON_SORTIE" CHARACTER VARYING(255),
    "IDENTIFIANT_BON_POUR" CHARACTER VARYING(25),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "BON_SORTIE_PKEY" PRIMARY KEY ("IDENTIFIANT_BON_SORIE")
);


CREATE TABLE "public"."BORDEREAU_LIVRAISON" (
    "IDENTIFIANT_B_L" CHARACTER VARYING(25) NOT NULL,
    "CONFORMITE_B_L" CHARACTER VARYING(3),
    "DATE_B_L" DATE,
    "DATE_ENREGISTREMENT" TIMESTAMP,
    "DESCRIPTION_B_L" CHARACTER VARYING(512),
    "LIEU_DE_LIVRAISON" CHARACTER VARYING(255),
    "NUMERO_B_L" CHARACTER VARYING(100),
    "REPRESENTANT_PRESTATAIRE" CHARACTER VARYING(255),
    "CODE_SECTION" CHARACTER VARYING(3),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "NINEA" CHARACTER VARYING(20),
    CONSTRAINT "BORDEREAU_LIVRAISON_PKEY" PRIMARY KEY ("IDENTIFIANT_B_L"),
    CONSTRAINT "UK_N83OWKMRVLXTHQ773N0JUIM69" UNIQUE ("NUMERO_B_L")
);


CREATE TABLE "public"."CONTROLE" (
    "DATE_CONTROLE" TIMESTAMP NOT NULL,
    "NUMERO_SERIE" CHARACTER VARYING(255) NOT NULL,
    "OBSERVATION_CONTROLE" CHARACTER VARYING(255),
    CONSTRAINT "CONTROLE_PKEY" PRIMARY KEY ("DATE_CONTROLE", "NUMERO_SERIE")
);


CREATE TABLE "public"."DOTATION_VEHICULE" (
    "IDENTIFIANT_D_V" CHARACTER VARYING(25) NOT NULL,
    "DATE_DOTATION" DATE,
    "CODE_ARTICLE_BON_SORTIE" INTEGER,
    "IDENTIFIANT_BON_SORTIE" CHARACTER VARYING(255),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "NUMERO_SERIE" CHARACTER VARYING(30),
    CONSTRAINT "DOTATION_VEHICULE_PKEY" PRIMARY KEY ("IDENTIFIANT_D_V")
);


CREATE TABLE "public"."FONCTIONS" (
    "CODE_FONCTION" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_FONCTION" CHARACTER VARYING(100),
    CONSTRAINT "FONCTIONS_PKEY" PRIMARY KEY ("CODE_FONCTION")
);


CREATE TABLE "public"."LIEU_STOCKAGE_VEHICULE" (
    "CODE_LIEU_VH" CHARACTER VARYING(3) NOT NULL,
    "LIBELLLE_LIEU_VH" CHARACTER VARYING(100),
    "NOMBRE_LIMITE_STOCKAGE_VH" INTEGER,
    CONSTRAINT "LIEU_STOCKAGE_VEHICULE_PKEY" PRIMARY KEY ("CODE_LIEU_VH")
);


CREATE TABLE "public"."MARQUE_ARME" (
    "CODE_MARQUE_ARME" CHARACTER VARYING(10) NOT NULL,
    "LIBELLE_MARQUE_ARME" CHARACTER VARYING(100),
    CONSTRAINT "MARQUE_ARME_PKEY" PRIMARY KEY ("CODE_MARQUE_ARME")
);


CREATE TABLE "public"."MARQUE_VEHICULE" (
    "CODE_MARQUE_VH" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_MARQUE_VH" CHARACTER VARYING(100),
    CONSTRAINT "MARQUE_VEHICULE_PKEY" PRIMARY KEY ("CODE_MARQUE_VH")
);


CREATE TABLE "public"."PAYS" (
    "CODE_PAYS" CHARACTER VARYING(3) NOT NULL,
    "LIBELLE_PAYS" CHARACTER VARYING(100),
    CONSTRAINT "PAYS_PKEY" PRIMARY KEY ("CODE_PAYS")
);


CREATE TABLE "public"."PRESTATAIRES" (
    "NINEA" CHARACTER VARYING(20) NOT NULL,
    "ADRESSE" CHARACTER VARYING(512),
    "ADRESSE_EMAIL" CHARACTER VARYING(100),
    "NUMERO_TELEPHONE" INTEGER,
    "RAISON_SOCIALE" CHARACTER VARYING(512),
    CONSTRAINT "PRESTATAIRES_PKEY" PRIMARY KEY ("NINEA")
);


CREATE TABLE "public"."PRESTATAIRES_SECTEUR" (
    "NINEA" CHARACTER VARYING(20) NOT NULL,
    "CODE_SECTEUR_ACTIVITE" CHARACTER VARYING(10) NOT NULL,
    CONSTRAINT "PRESTATAIRES_SECTEUR_PKEY" PRIMARY KEY ("NINEA", "CODE_SECTEUR_ACTIVITE")
);


CREATE TABLE "public"."SECTEUR_ACTIVITE" (
    "CODE_SECTEUR_ACTIVITE" CHARACTER VARYING(10) NOT NULL,
    "LIBELLE_SECTEUR_ACTIVITE" CHARACTER VARYING(255),
    CONSTRAINT "SECTEUR_ACTIVITE_PKEY" PRIMARY KEY ("CODE_SECTEUR_ACTIVITE")
);


CREATE TABLE "public"."SECTIONS" (
    "CODE_SECTION" CHARACTER VARYING(3) NOT NULL,
    "LIBELLE_SECTION" CHARACTER VARYING(100),
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3),
    CONSTRAINT "SECTIONS_PKEY" PRIMARY KEY ("CODE_SECTION")
);


CREATE TABLE "public"."TYPE_ARME" (
    "CODE_TYPE_ARME" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_TYPE_ARME" CHARACTER VARYING(255),
    CONSTRAINT "TYPE_ARME_PKEY" PRIMARY KEY ("CODE_TYPE_ARME")
);


CREATE TABLE "public"."TYPE_ENERGIE" (
    "CODE_TYPE_ENERGIE" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_TYPE_ENERGIE" CHARACTER VARYING(100),
    CONSTRAINT "TYPE_ENERGIE_PKEY" PRIMARY KEY ("CODE_TYPE_ENERGIE")
);


CREATE TABLE "public"."TYPE_OBJET" (
    "CODE_TYPE_OBJET" CHARACTER VARYING(5) NOT NULL,
    "LIBELLE_TYPE_OBJET" CHARACTER VARYING(100),
    "CODE_SECTION" CHARACTER VARYING(3),
    CONSTRAINT "TYPE_OBJET_PKEY" PRIMARY KEY ("CODE_TYPE_OBJET")
);


CREATE TABLE "public"."TYPE_UNITE_DOUANIERE" (
    "CODE_TYPE_UNITE_DOUANIERE" CHARACTER VARYING(5) NOT NULL,
    "LIBELLE_TYPE_UNITE_DOUANIERE" CHARACTER VARYING(100),
    CONSTRAINT "TYPE_UNITE_DOUANIERE_PKEY" PRIMARY KEY ("CODE_TYPE_UNITE_DOUANIERE")
);


CREATE TABLE "public"."TYPE_VEHICULE" (
    "CODE_TYPE_VEHICULE" CHARACTER VARYING(20) NOT NULL,
    "LIBELLE_TYPE_VEHICULE" CHARACTER VARYING(20),
    CONSTRAINT "TYPE_VEHICULE_PKEY" PRIMARY KEY ("CODE_TYPE_VEHICULE")
);


CREATE TABLE "public"."UNITE_DOUANIERE" (
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3) NOT NULL,
    "EFFECTIF_UNITE_DOUANIERE" INTEGER,
    "NOM_UNITE_DOUANIERE" CHARACTER VARYING(255),
    "NOMBRE_ARME" INTEGER,
    "NOMBRE_AUTOMOBILE" INTEGER,
    "NOMBRE_MATERIEL" INTEGER,
    "CODE_TYPE_UNITE_DOUANIERE" CHARACTER VARYING(5),
    CONSTRAINT "UNITE_DOUANIERE_PKEY" PRIMARY KEY ("CODE_UNITE_DOUANIERE")
);


CREATE TABLE "public"."UTILISATEUR" (
    "UTILISATEUR_ID" INTEGER NOT NULL,
    "IS_ACTIVE" BOOLEAN NOT NULL,
    "IS_NOT_LOCKED" BOOLEAN NOT NULL,
    "JOIN_DATE" TIMESTAMP,
    "LAST_LOGIN_DATE" TIMESTAMP,
    "LAST_LOGIN_DATE_DISPLAY" TIMESTAMP,
    "MOT_DE_PASSE" CHARACTER VARYING(255),
    "USER_NAME" CHARACTER VARYING(7),
    "CODE_FONCTION" CHARACTER VARYING(25),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "UTILISATEUR_PKEY" PRIMARY KEY ("UTILISATEUR_ID")
);


CREATE TABLE "public"."UTILISATEUR_AUTHORITY" (
    "CODE_AUTHORITY" INTEGER NOT NULL,
    "UTILISATEUR_ID" INTEGER NOT NULL,
    CONSTRAINT "UTILISATEUR_AUTHORITY_PKEY" PRIMARY KEY ("UTILISATEUR_ID", "CODE_AUTHORITY")
);


CREATE TABLE "public"."VEHICULE" (
    "NUMERO_SERIE" CHARACTER VARYING(30) NOT NULL,
    "DATE_MISE_EN_CIRCULATION" DATE,
    "LIBELLE_ETAT_VEHICULE" CHARACTER VARYING(10),
    "MODELE" CHARACTER VARYING(50),
    "NUMERO_CARTE_GRISE" CHARACTER VARYING(30),
    "NUMERO_IMMATRICULATION" CHARACTER VARYING(20),
    "CODE_ARTICLE_BON_ENTREE" INTEGER,
    "IDENTIFIANT_B_E" CHARACTER VARYING(255),
    "CODE_MARQUE" CHARACTER VARYING(25),
    "CODE_PAYS" CHARACTER VARYING(3),
    "CODE_TYPE_ENERGIE" CHARACTER VARYING(25),
    "CODE_TYPE_VEHICULE" CHARACTER VARYING(20),
    CONSTRAINT "VEHICULE_PKEY" PRIMARY KEY ("NUMERO_SERIE")
);


CREATE TABLE "public"."MAINTENANCE" (
    "IDENTIFIANT_MAINTENANCE" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : MSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "NUMERO_SERIE" CHARACTER VARYING(30),
    "DATE_DEBUT_MAINTENANCE" TIMESTAMP,
    "DATE_FIN_MAINTENANCE" TIMESTAMP,
    "TYPE_MAINTENANCE" CHARACTER VARYING(15),
    "OBSERVATION_MAINTENANCE" CHARACTER VARYING(512),
    CONSTRAINT "MAINTENANCE_PKEY" PRIMARY KEY ("IDENTIFIANT_MAINTENANCE")
);


CREATE TABLE "public"."ACCIDENT" (
    "IDENTIFIANT_ACCIDENT" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : MSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "DATE_INCIDENT" TIMESTAMP,
    "LIEU_INCIDENT" CHARACTER VARYING(512),
    "COMMENTAIRE_INCIDENT" CHARACTER VARYING(512),
    "NOMBRE_DECES" INTEGER,
    "NOMBRE_BLESSE" INTEGER,
    "RAPPORT_INCIDENT" BYTEA,
    CONSTRAINT "ACCIDENT_PKEY" PRIMARY KEY ("IDENTIFIANT_ACCIDENT")
);


CREATE TABLE "public"."CHANGEMENT_PIECE" (
    "IDENTIFIANT_MAINTENANCE" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : MSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "IDENTIFIANT_ACCIDENT" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : LSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "NOMBRE_PIECES_RECHANGEES" INTEGER,
    "REFERENCE_PIECES" CHARACTER VARYING(512),
    CONSTRAINT "CHANGEMENT_PIECE_PKEY" PRIMARY KEY ("IDENTIFIANT_REPARATION")
);


CREATE TABLE "public"."REPARATION" (
    "IDENTIFIANT_MAINTENANCE" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : MSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "IDENTIFIANT_ACCIDENT" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : LSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "MOTIF_REPARATION" CHARACTER VARYING(512),
    CONSTRAINT "REPARATION_PKEY" PRIMARY KEY ("IDENTIFIANT_MAINTENANCE", "IDENTIFIANT_ACCIDENT")
);


CREATE TABLE "public"."VIDANGE" (
    "IDENTIFIANT_MAINTENANCE" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : MSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "LIBELLE_HUILE" CHARACTER VARYING(512),
    "QUANTITE_MISE_VEHICULE" INTEGER,
    CONSTRAINT "VIDANGE_PKEY" PRIMARY KEY ("IDENTIFIANT_MAINTENANCE")
);


CREATE TABLE "public"."TOLERIE" (
    "IDENTIFIANT_MAINTENANCE" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : MSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "IDENTIFIANT_ACCIDENT" CHARACTER VARYING(25) NOT NULL, -- EXEMPLE : LSG202311121243214 (SG+HEURE EN TIMESTAMP)
    "DESCRIPTION_TOLERIE" CHARACTER VARYING(512),
    CONSTRAINT "TOLERIE_PKEY" PRIMARY KEY ("IDENTIFIANT_TOLERIE")
);



ALTER TABLE ONLY "public"."AGENT" ADD CONSTRAINT "FK6UO4H7RHN0BS7DR3H81RTJ55Y" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."AGENT" ADD CONSTRAINT "FKLSG4DT0DG2AU4HRD52JCJEE5Q" FOREIGN KEY (CODE_UNITE_DOUANIERE) REFERENCES UNITE_DOUANIERE(CODE_UNITE_DOUANIERE) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."ARTICLE_BON_ENTREE" ADD CONSTRAINT "FK1M4MO43NH47CUSTPL6F9SM30H" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."ARTICLE_BON_ENTREE" ADD CONSTRAINT "FK3JOTBYLCITC58MK3VFTXP3BKI" FOREIGN KEY (CODE_LIEU_VH) REFERENCES LIEU_STOCKAGE_VEHICULE(CODE_LIEU_VH) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."ARTICLE_BON_ENTREE" ADD CONSTRAINT "FKSAJTR4E61RJDG24JIJHNFJE4B" FOREIGN KEY (CODE_TYPE_OBJET) REFERENCES TYPE_OBJET(CODE_TYPE_OBJET) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."ARTICLE_BON_POUR" ADD CONSTRAINT "FKJLPVIQ6XKVQA50Y5KT5SUNIK4" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."ARTICLE_BON_POUR" ADD CONSTRAINT "FKOOY7AVGBU2T1YHE05WBREGROD" FOREIGN KEY (CODE_TYPE_OBJET) REFERENCES TYPE_OBJET(CODE_TYPE_OBJET) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."ARTICLE_BON_SORTIE" ADD CONSTRAINT "FKDU5P9UI862O7E13X2DU78D7VL" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."BON_ENTREE" ADD CONSTRAINT "FKG6GTMVAUM4XEW2C7XBQJQ9ED8" FOREIGN KEY (IDENTIFIANT_B_L) REFERENCES BORDEREAU_LIVRAISON(IDENTIFIANT_B_L) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."BON_POUR" ADD CONSTRAINT "FK1Q1QO11EBFF6QMGODXCU4O9ST" FOREIGN KEY (CODE_UNITE_DOUANIERE) REFERENCES UNITE_DOUANIERE(CODE_UNITE_DOUANIERE) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."BON_POUR" ADD CONSTRAINT "FK43WWFGFQIVCJE18OYVMWGHAXQ" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."BON_POUR" ADD CONSTRAINT "FKKH6PQUBEWX9NLAFC4O0U15ELJ" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."BON_SORTIE" ADD CONSTRAINT "FK2GWW0H1F2CD7CDK58EW10WQL0" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."BON_SORTIE" ADD CONSTRAINT "FKA1YVDDYP3OBK77A1FQOUVBXDY" FOREIGN KEY (IDENTIFIANT_BON_POUR) REFERENCES BON_POUR(IDENTIFIANT_BON_POUR) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."BORDEREAU_LIVRAISON" ADD CONSTRAINT "FK9NFRQJN6O2CN6F2S0JEBJY4RD" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."BORDEREAU_LIVRAISON" ADD CONSTRAINT "FKLLYEX0GCHKFEO1KNY1WFIAT2I" FOREIGN KEY (NINEA) REFERENCES PRESTATAIRES(NINEA) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."BORDEREAU_LIVRAISON" ADD CONSTRAINT "FKMKYIJG5TDM42O6EMET2CJ3CLS" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."DOTATION_VEHICULE" ADD CONSTRAINT "FK369D727JGD997P8WHN8YQV2DS" FOREIGN KEY (CODE_ARTICLE_BON_SORTIE, IDENTIFIANT_BON_SORTIE) REFERENCES ARTICLE_BON_SORTIE(CODE_ARTICLE_BON_SORTIE, IDENTIFIANT_BON_SORTIE) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."DOTATION_VEHICULE" ADD CONSTRAINT "FK78P66IOHICUBY5M74TVSMISKB" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."DOTATION_VEHICULE" ADD CONSTRAINT "FKG4B8PQXCJANPCURF0AVF3HFT4" FOREIGN KEY (NUMERO_SERIE) REFERENCES VEHICULE(NUMERO_SERIE) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."PRESTATAIRES_SECTEUR" ADD CONSTRAINT "FK30LVTRPR5GKIW3CV8PXIXFM0Q" FOREIGN KEY (CODE_SECTEUR_ACTIVITE) REFERENCES SECTEUR_ACTIVITE(CODE_SECTEUR_ACTIVITE) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."PRESTATAIRES_SECTEUR" ADD CONSTRAINT "FK7SH4GXDAA0D8R2623AII9H3CR" FOREIGN KEY (NINEA) REFERENCES PRESTATAIRES(NINEA) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."SECTIONS" ADD CONSTRAINT "FKQ7LGSKLXBP20KU1STGHG6IYQI" FOREIGN KEY (CODE_UNITE_DOUANIERE) REFERENCES UNITE_DOUANIERE(CODE_UNITE_DOUANIERE) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."TYPE_OBJET" ADD CONSTRAINT "FKLO9AWRORJGKP48PVWPFK1TKBY" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."UNITE_DOUANIERE" ADD CONSTRAINT "FKRMQO6IUO3MTC5EWY4QWXEHUN5" FOREIGN KEY (CODE_TYPE_UNITE_DOUANIERE) REFERENCES TYPE_UNITE_DOUANIERE(CODE_TYPE_UNITE_DOUANIERE) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."UTILISATEUR" ADD CONSTRAINT "FK3XM5O6UX34UJO3C6VK2VD85TV" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."UTILISATEUR" ADD CONSTRAINT "FKJWNVN45HMNXQA621AREMHTHE8" FOREIGN KEY (CODE_FONCTION) REFERENCES FONCTIONS(CODE_FONCTION) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."UTILISATEUR_AUTHORITY" ADD CONSTRAINT "FKFKS49EQJRVM6SKNERBQ5XDX51" FOREIGN KEY (UTILISATEUR_ID) REFERENCES UTILISATEUR(UTILISATEUR_ID) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."UTILISATEUR_AUTHORITY" ADD CONSTRAINT "FKM4WYQ2KW01DQR7Y1EBUXD1C2H" FOREIGN KEY (CODE_AUTHORITY) REFERENCES AUTHORITIES(CODE_AUTHORITY) NOT DEFERRABLE;

ALTER TABLE ONLY "public"."VEHICULE" ADD CONSTRAINT "FK8QTADOX10EKWUIVFOGCMG5A03" FOREIGN KEY (CODE_MARQUE) REFERENCES MARQUE_VEHICULE(CODE_MARQUE_VH) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."VEHICULE" ADD CONSTRAINT "FK9EW0GB55OE0NUCI8WKMVF3DMA" FOREIGN KEY (CODE_ARTICLE_BON_ENTREE, IDENTIFIANT_B_E) REFERENCES ARTICLE_BON_ENTREE(CODE_ARTICLE_BON_ENTREE, IDENTIFIANT_B_E) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."VEHICULE" ADD CONSTRAINT "FKIPAIC0O0EPPETWTTR3I51T542" FOREIGN KEY (CODE_TYPE_ENERGIE) REFERENCES TYPE_ENERGIE(CODE_TYPE_ENERGIE) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."VEHICULE" ADD CONSTRAINT "FKIT3TSR2XVG9LSX8A2WPBL9PJ" FOREIGN KEY (CODE_TYPE_VEHICULE) REFERENCES TYPE_VEHICULE(CODE_TYPE_VEHICULE) NOT DEFERRABLE;
ALTER TABLE ONLY "public"."VEHICULE" ADD CONSTRAINT "FKKYVS90NJN6TL5NWGPBI867IEJ" FOREIGN KEY (CODE_PAYS) REFERENCES PAYS(CODE_PAYS) NOT DEFERRABLE;

-- 2024-03-21 15:54:29.335097+00