CREATE TABLE "PUBLIC"."AGENT" (
    "MATRICULE_AGENT" CHARACTER VARYING(7) NOT NULL,
    
    "NOM_AGENT" CHARACTER VARYING(100),
    "EMAIL_AGENT" CHARACTER VARYING(100),
    "PRENOM_AGENT" CHARACTER VARYING(255),
    "CODE_SECTION" CHARACTER VARYING(3),
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3),
    "NUMERO_TELEPHONE_AGENT" INTEGER,
    CONSTRAINT "AGENT_CODE_AGENT_KEY" UNIQUE ("CODE_AGENT"),
    CONSTRAINT "AGENT_PKEY" PRIMARY KEY ("MATRICULE_AGENT")
);


CREATE TABLE "PUBLIC"."ARTICLE_BON_ENTREE" (
    "CODE_ARTICLE_BON_ENTREE" CHARACTER VARYING(25) NOT NULL,
    "IDENTIFIANT_B_E" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_ARTICLE_BON_ENTREE" CHARACTER VARYING(255),
    "CODE_LIEU_VH" CHARACTER VARYING(3),
    "QUANTITE_ENTREE" INTEGER,
    "CODE_TYPE_OBJET" CHARACTER VARYING(5),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "DATE_ENREGISTREMENT" TIMESTAMP(6),
    CONSTRAINT "ARTICLE_BON_ENTREE_PKEY" PRIMARY KEY ("CODE_ARTICLE_BON_ENTREE", "IDENTIFIANT_B_E")
);


CREATE TABLE "PUBLIC"."ARTICLE_BON_POUR" (
    "CODE_ARTICLE_BON_POUR" CHARACTER VARYING(25) NOT NULL,
    "IDENTIFIANT_B_P" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_ARTICLE_BON_POUR" CHARACTER VARYING(100),
    "QUANTITE_DEMANDEE" INTEGER,
    "CODE_TYPE_OBJET" CHARACTER VARYING(5),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "ARTICLE_BON_POUR_PKEY" PRIMARY KEY ("CODE_ARTICLE_BON_POUR", "IDENTIFIANT_B_P")
);


CREATE TABLE "PUBLIC"."ARTICLE_BON_SORTIE" (
    "CODE_ARTICLE_BON_SORTIE" CHARACTER VARYING(25) NOT NULL,
    "IDENTIFIANT_B_S" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_ARTICLE_BON_SORTIE" CHARACTER VARYING(100),
    "DATE_ARTICLE_BON_SORTIE" DATE,
    "QUANTITE_ACCORDEE" INTEGER,
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    CONSTRAINT "ARTICLE_BON_SORTIE_PKEY" PRIMARY KEY ("CODE_ARTICLE_BON_SORTIE", "IDENTIFIANT_B_S")
);


CREATE TABLE "PUBLIC"."AUTHORITIES" (
    "CODE_AUTHORITIES" CHARACTER VARYING(5) NOT NULL,
    "NAME_AUTHORITIES" CHARACTER VARYING(100),
    CONSTRAINT "AUTHORITIES_PKEY" PRIMARY KEY ("CODE_AUTHORITIES")
);


CREATE TABLE "PUBLIC"."BON_DE_SORTIE" (
    "IDENTIFIANT_B_S" CHARACTER VARYING(25) NOT NULL,
    "NUMERO_B_S" CHARACTER VARYING(100),
    "DESCRIPTION_B_S" CHARACTER VARYING(255),
    "DATE_B_S" DATE,
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "IDENTIFIANT_B_P" CHARACTER VARYING(25),
    CONSTRAINT "BON_DE_SORTIE_PKEY" PRIMARY KEY ("IDENTIFIANT_B_S")
);


CREATE TABLE "PUBLIC"."BON_ENTREE" (
    "DATE_BON_ENTREE" DATE,
    "IDENTIFIANT_B_E" CHARACTER VARYING(25) NOT NULL,
    "IDENTIFIANT_B_L" CHARACTER VARYING(25),
    "NUMERO_B_E" CHARACTER VARYING(100),
    "LIBELLE_BON_ENTREE" CHARACTER VARYING(255),
    "OBSERVATION_BON_ENTREE" CHARACTER VARYING(255),
    CONSTRAINT "BON_ENTREE_NUMERO_B_E_KEY" UNIQUE ("NUMERO_B_E"),
    CONSTRAINT "BON_ENTREE_PKEY" PRIMARY KEY ("IDENTIFIANT_B_E")
);


CREATE TABLE "PUBLIC"."BON_POUR" (
    "IDENTIFIANT_B_P" CHARACTER VARYING(25) NOT NULL,
    "DESCRIPTION_B_P" CHARACTER VARYING(255),
    "ETAT_B_P" CHARACTER VARYING(10),
    "CODE_SECTION" CHARACTER VARYING(3),
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3),
    "NUMERO_COURRIEL_ORIGINE" INTEGER,
    "DATE_COURRIEL_ORIGINE" DATE,
    "OBJECT_COURRIEL_ORIGINE" CHARACTER VARYING(255),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "DATE_ENREGISTREMENT" TIMESTAMP,
    "NUMERO_ARRIVE_B_L_M" INTEGER,
    "NUMERO_ARRIVE_D_L_F" INTEGER,
    "NUMERO_ARRIVE_SECTION" INTEGER,
    "DATE_ARRIVE_B_L_M" DATE,
    "DATE_ARRIVE_D_L_F" DATE,
    "DATE_ARRIVE_SECTION" DATE,
    "OBSERVATION_B_L_M" CHARACTER VARYING(255),
    "OBSERVATION_D_L_F" CHARACTER VARYING(255),
    "OBSERVATION_SECTION" CHARACTER VARYING(255),
    CONSTRAINT "BON_POUR_PKEY" PRIMARY KEY ("IDENTIFIANT_B_P")
);


CREATE TABLE "PUBLIC"."BORDEREAU_LIVRAISON" (
    "IDENTIFIANT_B_L" CHARACTER VARYING(25) NOT NULL,
    "NUMERO_B_L" CHARACTER VARYING(100),
    "DATE_B_L" DATE,
    "DESCRIPTION_B_L" CHARACTER VARYING(512),
    "LIEU_DE_LIVRAISON" CHARACTER VARYING(255),
    "REPRESENTANT_PRESTATAIRE" CHARACTER VARYING(255),
    "CODE_SECTION" CHARACTER VARYING(3),
    "CONFORMITE_B_L" CHARACTER VARYING(3),
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "DATE_ENREGISTREMENT" TIMESTAMP,
    "NINEA" CHARACTER VARYING(20),
    CONSTRAINT "BORDEREAU_LIVRAISON_NUMERO_B_L_KEY" UNIQUE ("NUMERO_B_L"),
    CONSTRAINT "BORDEREAU_LIVRAISON_PKEY" PRIMARY KEY ("IDENTIFIANT_B_L")
);



CREATE TABLE "PUBLIC"."CONTROLE" (
    "NUMERO_IMMATRICULATION" CHARACTER VARYING(25) NOT NULL,
    "DATE_CONTROLE" DATE NOT NULL,
    "OBSERVATION_CONTROLE" CHARACTER VARYING(255),
    CONSTRAINT "CONTROLE_PKEY" PRIMARY KEY ("NUMERO_IMMATRICULATION", "DATE_CONTROLE")
);


CREATE TABLE "PUBLIC"."DOTATION_VEHICULE" (
    "IDENTIFIANT_D_V" CHARACTER VARYING(25) NOT NULL,
    "NUMERO_SERIE" CHARACTER VARYING(30) NOT NULL,
    "DATE_DOTATION" DATE,
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "IDENTIFIANT_B_S" CHARACTER VARYING(25),
    "CODE_ARTICLE_BON_SORTIE" CHARACTER VARYING(25),
    CONSTRAINT "DOTATION_VEHICULE_PKEY" PRIMARY KEY ("IDENTIFIANT_D_V")
);


CREATE TABLE "PUBLIC"."FONCTION_AGENT" (
    "CODE_FONCTION_AGENT" CHARACTER VARYING(10) NOT NULL,
    "LIBELLE_FONCTION_AGENT" CHARACTER VARYING(100),
    CONSTRAINT "FONCTION_AGENT_PKEY" PRIMARY KEY ("CODE_FONCTION_AGENT")
);


CREATE TABLE "PUBLIC"."LIEU_STOCKAGE_VEHICULE" (
    "CODE_LIEU_VH" CHARACTER VARYING(3) NOT NULL,
    "LIBELLLE_LIEU_VH" CHARACTER VARYING(100),
    "NOMBRE_LIMITE_STOCKAGE_VH" INTEGER,
    CONSTRAINT "LIEU_STOCKAGE_VEHICULE_PKEY" PRIMARY KEY ("CODE_LIEU_VH")
);


CREATE TABLE "PUBLIC"."MARQUE_ARME" (
    "CODE_MARQUE_ARME" CHARACTER VARYING(10) NOT NULL,
    "LIBELLE_MARQUE_ARME" CHARACTER VARYING(100),
    CONSTRAINT "MARQUE_ARME_PKEY" PRIMARY KEY ("CODE_MARQUE_ARME")
);


CREATE TABLE "PUBLIC"."MARQUE_VEHICULE" (
    "CODE_MARQUE_VH" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_MARQUE_VH" CHARACTER VARYING(100),
    CONSTRAINT "MARQUE_VEHICULE_PKEY" PRIMARY KEY ("CODE_MARQUE_VH")
);


CREATE TABLE "PUBLIC"."PAYS" (
    "CODE_PAYS" CHARACTER VARYING(3) NOT NULL,
    "LIBELLE_PAYS" CHARACTER VARYING(100),
    CONSTRAINT "PAYS_PKEY" PRIMARY KEY ("CODE_PAYS")
);


CREATE TABLE "PUBLIC"."PRESTATAIRES" (
    "NINEA" CHARACTER VARYING(20) NOT NULL,
    "ADRESSE_EMAIL" CHARACTER VARYING(100),
    "ADRESSE" CHARACTER VARYING(512),
    "RAISON_SOCIALE" CHARACTER VARYING(512),
    "NUMERO_TELEPHONE" INTEGER,
    CONSTRAINT "PRESTATAIRES_PKEY" PRIMARY KEY ("NINEA")
);


CREATE TABLE "PUBLIC"."SECTEUR_ACTIVITE" (
    "CODE_SECTEUR_ACTIVITE" CHARACTER VARYING(10) NOT NULL,
    "LIBELLE_SECTEUR_ACTIVITE" CHARACTER VARYING(255),
    CONSTRAINT "SECTEUR_ACTIVITE_PKEY" PRIMARY KEY ("CODE_SECTEUR_ACTIVITE")
);


CREATE TABLE "PUBLIC"."PRESTATAIRES_SECTEUR" (
    "CODE_SECTEUR_ACTIVITE" CHARACTER VARYING(10) NOT NULL,
    "NINEA" CHARACTER VARYING(20) NOT NULL,
    CONSTRAINT "PRESTATAIRES_SECTEUR_PKEY" PRIMARY KEY ("CODE_SECTEUR_ACTIVITE", "NINEA")
);


CREATE TABLE "PUBLIC"."SECTIONS" (
    "CODE_SECTION" CHARACTER VARYING(3) NOT NULL,
    "LIBELLE_SECTION" CHARACTER VARYING(100),
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3) NOT NULL,
    CONSTRAINT "SECTIONS_PKEY" PRIMARY KEY ("CODE_SECTION")
);

CREATE TABLE "PUBLIC"."TYPE_ARME" (
    "CODE_TYPE_ARME" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_TYPE_ARME" CHARACTER VARYING(255),
    CONSTRAINT "TYPE_ARME_PKEY" PRIMARY KEY ("CODE_TYPE_ARME")
);

CREATE TABLE "PUBLIC"."TYPE_ENERGIE" (
    "CODE_TYPE_ENERGIE" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_TYPE_ENERGIE" CHARACTER VARYING(100),
    CONSTRAINT "TYPE_ENERGIE_PKEY" PRIMARY KEY ("CODE_TYPE_ENERGIE")
);

CREATE TABLE "PUBLIC"."TYPE_MATERIEL" (
    "CODE_TYPE_MATERIEL" CHARACTER VARYING(25) NOT NULL,
    "LIBELLE_TYPE_MATERIEL" CHARACTER VARYING(255),
    CONSTRAINT "TYPE_MATERIEL_PKEY" PRIMARY KEY ("CODE_TYPE_MATERIEL")
);

CREATE TABLE "PUBLIC"."TYPE_OBJET" (
    "CODE_TYPE_OBJET" CHARACTER VARYING(5) NOT NULL,
    "LIBELLE_TYPE_OBJET" CHARACTER VARYING(100),
    "CODE_SECTION" CHARACTER VARYING(3),
    CONSTRAINT "TYPE_OBJET_PKEY" PRIMARY KEY ("CODE_TYPE_OBJET")
);

CREATE TABLE "PUBLIC"."TYPE_UNITE_DOUANIERE" (
    "CODE_TYPE_UNITE_DOUANIERE" CHARACTER VARYING(5) NOT NULL,
    "LIBELLE_TYPE_UNITE_DOUANIERE" CHARACTER VARYING(100),
    CONSTRAINT "TYPE_UNITE_DOUANIERE_PKEY" PRIMARY KEY ("CODE_TYPE_UNITE_DOUANIERE")
);

CREATE TABLE "PUBLIC"."TYPE_VEHICULE" (
    "CODE_TYPE_VEHICULE" CHARACTER VARYING(20) NOT NULL,
    "LIBELLE_TYPE_VEHICULE" CHARACTER VARYING(20),
    CONSTRAINT "TYPE_VEHICULE_PKEY" PRIMARY KEY ("CODE_TYPE_VEHICULE")
);

CREATE TABLE "PUBLIC"."UNITE_DOUANIERE" (
    "CODE_UNITE_DOUANIERE" CHARACTER VARYING(3) NOT NULL,
    "NOM_UNITE_DOUANIERE" CHARACTER VARYING(255),
    "EFFECTIF_UNITE_DOUANIERE" INTEGER,
    "NOMBRE_ARME" INTEGER,
    "NOMBRE_AUTOMOBILE" INTEGER,
    "NOMBRE_MATERIEL" INTEGER,
    "CODE_TYPE_UNITE_DOUANIERE" CHARACTER VARYING(5),
    "CODE_UNITE_HIERARCHIQUE" CHARACTER VARYING(3),
    CONSTRAINT "UNITE_DOUANIERE_PKEY" PRIMARY KEY ("CODE_UNITE_DOUANIERE")
);

CREATE TABLE "PUBLIC"."UTILISATEUR" (
    "UTILISATEUR_ID" CHARACTER VARYING(25) NOT NULL,
    "MATRICULE_AGENT" CHARACTER VARYING(7),
    "USER_NAME" CHARACTER VARYING(7),
    "JOIN_DATE" TIMESTAMP,
    "LAST_LOGIN_DATE" TIMESTAMP,
    "LAST_LOGIN_DATE_DISPLAY" TIMESTAMP,
    "PWD" CHARACTER VARYING(255),
    "CODE_AUTHORITIES" CHARACTER VARYING(5),
    "IS_ACTIVE" BOOLEAN NOT NULL,
    "IS_NOT_LOCKED" BOOLEAN NOT NULL,
    CONSTRAINT "UTILISATEUR_PKEY" PRIMARY KEY ("UTILISATEUR_ID")
);

CREATE TABLE "PUBLIC"."VEHICULE" (
    "NUMERO_SERIE" CHARACTER VARYING(30) NOT NULL,
    "NUMERO_IMMATRICULATION" CHARACTER VARYING(20),
    "CODE_ARTICLE_BON_ENTREE" CHARACTER VARYING(25),
    "CODE_MARQUE" CHARACTER VARYING(25),
    "CODE_TYPE_ENERGIE" CHARACTER VARYING(25),
    "IDENTIFIANT_B_E" CHARACTER VARYING(25),
    "NUMERO_CARTE_GRISE" CHARACTER VARYING(30),
    "CODE_TYPE_VEHICULE" CHARACTER VARYING(20),
    "MODELE" CHARACTER VARYING(50),
    "CODE_PAYS" CHARACTER VARYING(3),
    "DATE_MISE_EN_CIRCULATION" DATE,
    "CODE_ETAT" CHARACTER VARYING(10),
    CONSTRAINT "VEHICULE_PKEY" PRIMARY KEY ("NUMERO_SERIE")
);

======================================




ALTER TABLE ONLY "PUBLIC"."AGENT" ADD CONSTRAINT "FK6UO4H7RHN0BS7DR3H81RTJ55Y" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."AGENT" ADD CONSTRAINT "FKLSG4DT0DG2AU4HRD52JCJEE5Q" FOREIGN KEY (CODE_UNITE_DOUANIERE) REFERENCES UNITE_DOUANIERE(CODE_UNITE_DOUANIERE) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_ENTREE" ADD CONSTRAINT "FK1M4MO43NH47CUSTPL6F9SM30H" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_ENTREE" ADD CONSTRAINT "FK3JOTBYLCITC58MK3VFTXP3BKI" FOREIGN KEY (CODE_LIEU_VH) REFERENCES LIEU_STOCKAGE_VEHICULE(CODE_LIEU_VH) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_ENTREE" ADD CONSTRAINT "FKJF7S6YS77CWV0LTBV7ICA1YJV" FOREIGN KEY (IDENTIFIANT_B_E) REFERENCES BON_ENTREE(IDENTIFIANT_B_E) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_ENTREE" ADD CONSTRAINT "FKSAJTR4E61RJDG24JIJHNFJE4B" FOREIGN KEY (CODE_TYPE_OBJET) REFERENCES TYPE_OBJET(CODE_TYPE_OBJET) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_POUR" ADD CONSTRAINT "FKHMB770O63O2FAJDV3TPUXQVFC" FOREIGN KEY (IDENTIFIANT_B_P) REFERENCES BON_POUR(IDENTIFIANT_B_P) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_POUR" ADD CONSTRAINT "FKJLPVIQ6XKVQA50Y5KT5SUNIK4" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_POUR" ADD CONSTRAINT "FKOOY7AVGBU2T1YHE05WBREGROD" FOREIGN KEY (CODE_TYPE_OBJET) REFERENCES TYPE_OBJET(CODE_TYPE_OBJET) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_SORTIE" ADD CONSTRAINT "FKDU5P9UI862O7E13X2DU78D7VL" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."ARTICLE_BON_SORTIE" ADD CONSTRAINT "FKESVKYN5TDQBWMJVBLUJV1P7SR" FOREIGN KEY (IDENTIFIANT_B_S) REFERENCES BON_DE_SORTIE(IDENTIFIANT_B_S) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."BON_DE_SORTIE" ADD CONSTRAINT "FK9UWHE0X9MHS9AX7Q0HCAI2NUU" FOREIGN KEY (IDENTIFIANT_B_P) REFERENCES BON_POUR(IDENTIFIANT_B_P) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."BON_DE_SORTIE" ADD CONSTRAINT "FKH6WHU0YVRU8BH7UR38EV8DFQ6" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."BON_ENTREE" ADD CONSTRAINT "FKG6GTMVAUM4XEW2C7XBQJQ9ED8" FOREIGN KEY (IDENTIFIANT_B_L) REFERENCES BORDEREAU_LIVRAISON(IDENTIFIANT_B_L) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."BON_POUR" ADD CONSTRAINT "FK1Q1QO11EBFF6QMGODXCU4O9ST" FOREIGN KEY (CODE_UNITE_DOUANIERE) REFERENCES UNITE_DOUANIERE(CODE_UNITE_DOUANIERE) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."BON_POUR" ADD CONSTRAINT "FK43WWFGFQIVCJE18OYVMWGHAXQ" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."BON_POUR" ADD CONSTRAINT "FKKH6PQUBEWX9NLAFC4O0U15ELJ" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."BORDEREAU_LIVRAISON" ADD CONSTRAINT "FK9NFRQJN6O2CN6F2S0JEBJY4RD" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."BORDEREAU_LIVRAISON" ADD CONSTRAINT "FKLLYEX0GCHKFEO1KNY1WFIAT2I" FOREIGN KEY (NINEA) REFERENCES PRESTATAIRES(NINEA) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."BORDEREAU_LIVRAISON" ADD CONSTRAINT "FKMKYIJG5TDM42O6EMET2CJ3CLS" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."DOTATION_VEHICULE" ADD CONSTRAINT "FK4X5A1U8FVCY2BAJSW05G552U6" FOREIGN KEY (CODE_ARTICLE_BON_SORTIE, IDENTIFIANT_B_S) REFERENCES ARTICLE_BON_SORTIE(CODE_ARTICLE_BON_SORTIE, IDENTIFIANT_B_S) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."DOTATION_VEHICULE" ADD CONSTRAINT "FK78P66IOHICUBY5M74TVSMISKB" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."DOTATION_VEHICULE_VEHICULE" ADD CONSTRAINT "FKB911U0EJ5GFCYF7Q6MODN9HW4" FOREIGN KEY (NUMERO_SERIE) REFERENCES VEHICULE(NUMERO_SERIE) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."DOTATION_VEHICULE_VEHICULE" ADD CONSTRAINT "FKJT5NJX4WCODXUS0QN7XATLOC7" FOREIGN KEY (IDENTIFIANT_D_V) REFERENCES DOTATION_VEHICULE(IDENTIFIANT_D_V) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."PRESTATAIRES_SECTEUR" ADD CONSTRAINT "FK30LVTRPR5GKIW3CV8PXIXFM0Q" FOREIGN KEY (CODE_SECTEUR_ACTIVITE) REFERENCES SECTEUR_ACTIVITE(CODE_SECTEUR_ACTIVITE) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."PRESTATAIRES_SECTEUR" ADD CONSTRAINT "FK7SH4GXDAA0D8R2623AII9H3CR" FOREIGN KEY (NINEA) REFERENCES PRESTATAIRES(NINEA) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."TYPE_OBJET" ADD CONSTRAINT "FKLO9AWRORJGKP48PVWPFK1TKBY" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."UNITE_DOUANIERE" ADD CONSTRAINT "FKRMQO6IUO3MTC5EWY4QWXEHUN5" FOREIGN KEY (CODE_TYPE_UNITE_DOUANIERE) REFERENCES TYPE_UNITE_DOUANIERE(CODE_TYPE_UNITE_DOUANIERE) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."UNITE_DOUANIERE_SECTIONS" ADD CONSTRAINT "FKET14YNIW9FNGNPB3056RK4P6" FOREIGN KEY (CODE_SECTION) REFERENCES SECTIONS(CODE_SECTION) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."UNITE_DOUANIERE_SECTIONS" ADD CONSTRAINT "FKJUWCURDGWB9PN61E66M5O5F4U" FOREIGN KEY (CODE_UNITE_DOUANIERE) REFERENCES UNITE_DOUANIERE(CODE_UNITE_DOUANIERE) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."UTILISATEUR" ADD CONSTRAINT "FK3XM5O6UX34UJO3C6VK2VD85TV" FOREIGN KEY (MATRICULE_AGENT) REFERENCES AGENT(MATRICULE_AGENT) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."UTILISATEUR_AUTHORITY" ADD CONSTRAINT "FKC85DTPOIV6WI8JXUOBDT3GDN5" FOREIGN KEY (CODE) REFERENCES AUTHORITIES(CODE) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."UTILISATEUR_AUTHORITY" ADD CONSTRAINT "FKFKS49EQJRVM6SKNERBQ5XDX51" FOREIGN KEY (UTILISATEUR_ID) REFERENCES UTILISATEUR(UTILISATEUR_ID) NOT DEFERRABLE;

ALTER TABLE ONLY "PUBLIC"."VEHICULE" ADD CONSTRAINT "FK8QTADOX10EKWUIVFOGCMG5A03" FOREIGN KEY (CODE_MARQUE) REFERENCES MARQUE_VEHICULE(CODE_MARQUE) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."VEHICULE" ADD CONSTRAINT "FK9EW0GB55OE0NUCI8WKMVF3DMA" FOREIGN KEY (CODE_ARTICLE_BON_ENTREE, IDENTIFIANT_B_E) REFERENCES ARTICLE_BON_ENTREE(CODE_ARTICLE_BON_ENTREE, IDENTIFIANT_B_E) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."VEHICULE" ADD CONSTRAINT "FKIPAIC0O0EPPETWTTR3I51T542" FOREIGN KEY (CODE_TYPE_ENERGIE) REFERENCES TYPE_ENERGIE(CODE_TYPE_ENERGIE) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."VEHICULE" ADD CONSTRAINT "FKIT3TSR2XVG9LSX8A2WPBL9PJ" FOREIGN KEY (CODE_TYPE_VEHICULE) REFERENCES TYPE_VEHICULE(CODE_TYPE_VEHICULE) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."VEHICULE" ADD CONSTRAINT "FKKYVS90NJN6TL5NWGPBI867IEJ" FOREIGN KEY (CODE_PAYS) REFERENCES PAYS(CODE_PAYS) NOT DEFERRABLE;
ALTER TABLE ONLY "PUBLIC"."VEHICULE" ADD CONSTRAINT "FKLSNFLJ46N2V0TD92L7NN2ER43" FOREIGN KEY (CODE_ETAT) REFERENCES ETAT_VEHICULE(CODE_ETAT) NOT DEFERRABLE;

-- 2024-02-26 12:31:13.637956+00
