export enum FonctionUtilisateur {

  ADMIN = 'ADMINISTRATEUR',
  CSA = 'CHEF SECTION ARMEMENT',
  ASA = 'AGENT SECTION ARMEMENT',
  CSG = 'CHEF SECTION GARAGE',
  ASG = 'AGENT SECTION GARAGE',
  CSM = 'CHEF SECTION MATÉRIEL',
  ASM = 'AGENT SECTION MATÉRIEL',
  BLM = 'CHEF BLM',
  DLF = 'DIRECTEUR DLF',
  BAF = 'BUREAU ADMINISTRATIF ET FINANCIER'

}
